# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish Modbus.Protocol

on:
  push:
    branches: [ "master" ]
    paths:
      - "**/*.csproj"

jobs:
  check_version:    
    uses: Abaddax/workflows/.github/workflows/dotnet.check_version.yml@master
    with:
      CSPROJ_PATH: Modbus.Protocol/Modbus.Protocol.csproj
      
  ci:    
    needs: [check_version]
    if: needs.check_version.outputs.version_changed == 'true'
    uses: ./.github/workflows/ci.yml
  
  publish:  
    needs: [check_version, ci]
    if: needs.check_version.outputs.version_changed == 'true'
    uses: ./.github/workflows/publish.modbus.protocol.nuget.yml
    permissions:
      contents: write
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
