# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish Modbus.TCP NuGet-Package

on:
  workflow_call:
    secrets:
      NUGET_API_KEY:
        required: true
  workflow_dispatch:

jobs:  
  publish_nuget:  
    uses: Abaddax/workflows/.github/workflows/dotnet.publish_nuget.yml@master
    with:
      CSPROJ_PATH: Modbus.TCP/Modbus.TCP.csproj
      TAG_PREFIX: Modbus.TCP-v
    permissions:
      contents: write
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
